# noinspection PyStatementEffect
{
    'name': 'Trilab KSeF',
    'author': 'Trilab',
    'website': 'https://trilab.pl',
    'version': '15.0.3.0.7',
    'category': 'Accounting',
    'summary': 'Invoice Integration with Polish Government',
    'description': 'Invoice Integration with Polish Government using KSeF API.',
    'depends': ['trilab_invoice', 'trilab_jpk_base', 'account_edi'],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/ir_cron.xml',
        'data/mail_activity_type.xml',
        'report/invoice.xml',
        'views/account_move.xml',
        'views/account_payment_term.xml',
        'views/account_tax.xml',
        'views/res_partner.xml',
        'views/ksef_settings.xml',
        'views/res_config_settings.xml',
        'views/report_invoice.xml',
        'wizard/batch_import_wizard.xml',
    ],
    'assets': {'web.report_assets_common': ['trilab_ksef/static/src/scss/style.scss']},
    'images': ['static/description/banner.png'],
    'post_init_hook': 'post_init',
    'uninstall_hook': 'uninstall',
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'OPL-1',
    'price': 400.0,
    'currency': 'EUR',
}
