{
    "name": "Product Cost Edit Group",
    "summary": "Group for cost modification access on product",
    "author": "ERP Ukraine LLC, VentorTech",
    "website": "https://erp.co.ua",
    "support": "support@erp.co.ua",
    "license": "LGPL-3",
    "category": "Hidden",
    "version": "19.0.1.0.0",
    "depends": ["stock_account"],
    "data": ["security/stock_account_security.xml"],
    "installable": True,
    "auto_install": False,
    "application": False,
}
