# noinspection PyStatementEffect
{
    'name': 'Trilab Invoice PL',
    'author': 'Trilab',
    'website': 'https://trilab.pl',
    'version': '18.0.3.1.1',
    'category': 'Accounting',
    'summary': 'Base module to manage invoice in PL',
    'description': """Base module to manage invoices and invoice correction
    according to Polish law and best practices""",
    'depends': ['account', 'sale', 'sale_management', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/account_move_reversal.xml',
        'wizard/invoice.xml',
        'wizard/res_config_settings.xml',
        'views/account_move.xml',
        'views/report_invoice.xml',
        'views/sale_order.xml',
        'reports/sale_order.xml',
    ],
    'images': ['static/description/banner.png', 'static/description/invoice.png'],
    'assets': {'web.report_assets_common': ['trilab_invoice/static/src/scss/layout_boxed.scss']},
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'OPL-1',
    'price': 140.0,
    'currency': 'EUR',
}
