from . import account_invoice
from . import account_intrastat_report
from . import efarmer_client_type
from . import product_category
from . import product_product
from . import product_template
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import stock_picking
from . import ir_actions_report
from . import stock_warehouse
